name: Rust CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    types: [ edited ]

  pull_request:
    branches: [ "master" ]
    types: [ opened, synchronize ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # provided automatically by GitHub
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with: { name: dist }
      - id: create_release
        uses: elgohr/Github-Release-Action@v5
        with:
          title: Dev Build ${{ github.sha }}
          tag: dev-${{ github.sha }}
          prerelease: true